// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: auth/grpc/auth.proto

package protocAuth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_auth_grpc_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_auth_grpc_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type TokenStr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenStr) Reset() {
	*x = TokenStr{}
	mi := &file_auth_grpc_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenStr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenStr) ProtoMessage() {}

func (x *TokenStr) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenStr.ProtoReflect.Descriptor instead.
func (*TokenStr) Descriptor() ([]byte, []int) {
	return file_auth_grpc_auth_proto_rawDescGZIP(), []int{1}
}

func (x *TokenStr) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_auth_grpc_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_auth_grpc_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_auth_grpc_auth_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_auth_grpc_auth_proto protoreflect.FileDescriptor

const file_auth_grpc_auth_proto_rawDesc = "" +
	"\n" +
	"\x14auth/grpc/auth.proto\x12\bauthGrpc\":\n" +
	"\bUserInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\" \n" +
	"\bTokenStr\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x1d\n" +
	"\x05Error\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xb6\x01\n" +
	"\n" +
	"Authorizer\x12:\n" +
	"\x10AuthenticateUser\x12\x12.authGrpc.UserInfo\x1a\x12.authGrpc.TokenStr\x126\n" +
	"\fRegisterUser\x12\x12.authGrpc.UserInfo\x1a\x12.authGrpc.TokenStr\x124\n" +
	"\rAuthorizeUser\x12\x12.authGrpc.TokenStr\x1a\x0f.authGrpc.ErrorBJZHgithub.com/zenrot/CryptoService/internal/auth/grpcAuth/protoc;protocAuthb\x06proto3"

var (
	file_auth_grpc_auth_proto_rawDescOnce sync.Once
	file_auth_grpc_auth_proto_rawDescData []byte
)

func file_auth_grpc_auth_proto_rawDescGZIP() []byte {
	file_auth_grpc_auth_proto_rawDescOnce.Do(func() {
		file_auth_grpc_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_grpc_auth_proto_rawDesc), len(file_auth_grpc_auth_proto_rawDesc)))
	})
	return file_auth_grpc_auth_proto_rawDescData
}

var file_auth_grpc_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auth_grpc_auth_proto_goTypes = []any{
	(*UserInfo)(nil), // 0: authGrpc.UserInfo
	(*TokenStr)(nil), // 1: authGrpc.TokenStr
	(*Error)(nil),    // 2: authGrpc.Error
}
var file_auth_grpc_auth_proto_depIdxs = []int32{
	0, // 0: authGrpc.Authorizer.AuthenticateUser:input_type -> authGrpc.UserInfo
	0, // 1: authGrpc.Authorizer.RegisterUser:input_type -> authGrpc.UserInfo
	1, // 2: authGrpc.Authorizer.AuthorizeUser:input_type -> authGrpc.TokenStr
	1, // 3: authGrpc.Authorizer.AuthenticateUser:output_type -> authGrpc.TokenStr
	1, // 4: authGrpc.Authorizer.RegisterUser:output_type -> authGrpc.TokenStr
	2, // 5: authGrpc.Authorizer.AuthorizeUser:output_type -> authGrpc.Error
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_grpc_auth_proto_init() }
func file_auth_grpc_auth_proto_init() {
	if File_auth_grpc_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_grpc_auth_proto_rawDesc), len(file_auth_grpc_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_grpc_auth_proto_goTypes,
		DependencyIndexes: file_auth_grpc_auth_proto_depIdxs,
		MessageInfos:      file_auth_grpc_auth_proto_msgTypes,
	}.Build()
	File_auth_grpc_auth_proto = out.File
	file_auth_grpc_auth_proto_goTypes = nil
	file_auth_grpc_auth_proto_depIdxs = nil
}
